main:
  - name: About Me
    url: /
    weight: 10
  - name: News
    url: /#news
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30
  - name: Educations
    url: /#educations
    weight: 40
  - name: Invited Talks
    url: /#talks
    weight: 50
